name: hepstats-test
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - iminuit
  - uproot
  - matplotlib
  - tensorflow =>2.4
  - tensorflow-probability
  - asdf
  - pip:
      - zfit =>0.6.3
