# Copyright (c) 2019, Henry Schreiner.
#
# Distributed under the 3-clause BSD license, see accompanying file LICENSE
# or https://github.com/scikit-hep/azure-wheel-helpers for details.

# Template - you must copy (or symlink) this to your .ci folder
# Packages usually will have a little custom code in here, and
# can override any of the templates from here, as well

# Triggers can be overridden in the GUI. Suggested use follows:
trigger:
  tags:
    include:
    - v*

# For a master-develop workflow:
pr:
   - master
 trigger:
   - master

# Either set these value here, or in the GUI
# variables:
   package_name: skstats    # This is the output name, - is replaced by _
   many_linux_base: "quay.io/pypa/manylinux1_" # Should be quay.io/pypa/manylinux1_ or skhep/manylinuxgcc-

jobs:

- job: LinuxSDist
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    python.architecture: 'none'
  steps:
    - script: |
        python -m pip install setuptools
        python setup.py sdist
      displayName: Publish sdist
    - template: azure-wheel-helpers/azure-publish-dist.yml

- job: ManyLinux
  strategy:
    matrix:
      64Bit2010:
        arch: x86_64
        plat: manylinux2010_x86_64
        image: quay.io/pypa/manylinux2010_x86_64
        python.architecture: x64
      64Bit:
        arch: x86_64
        plat: manylinux1_x86_64
        image: $(many_linux_base)x86_64
        python.architecture: x64
      32Bit:
        arch: i686
        plat: manylinux1_i686
        image: $(many_linux_base)i686
        python.architecture: x86
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - template: azure-wheel-helpers/azure-manylinux-wheels.yml
    - template: azure-wheel-helpers/azure-publish-dist.yml

- job: macOS
  variables:
    python.architecture: 'x64'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'macOS-latest'
  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - bash: sudo chown -R $USER $CONDA
      displayName: Take ownership of conda installation
    - template: azure-setup.yml
    - template: azure-wheel-helpers/azure-steps.yml
    - template: azure-tests.yml
    - template: azure-wheel-helpers/azure-publish-dist.yml

- job: Windows
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37:
        python.version: '3.7'
        python.architecture: 'x64'
      Python36_32:
        python.version: '3.6'
        python.architecture: 'x86'
      Python37_32:
        python.version: '3.7'
        python.architecture: 'x86'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH
    - template: azure-setup.yml
    - template: azure-wheel-helpers/azure-steps.yml
    - template: azure-tests.yml
    - template: azure-wheel-helpers/azure-publish-dist.yml
